<template>
    <div class="flex h-screen items-center justify-center">
        <div class="loadingio-spinner-ripple-b5yvo04stvj"><div class="ldio-allva3punxa">
<div></div><div></div>
</div></div>
    </div>
  
</template>

<script>
export default {

}
</script>


<style type="text/css">
@keyframes ldio-allva3punxa {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 18px;
    left: 18px;
    width: 156px;
    height: 156px;
    opacity: 0;
  }
}.ldio-allva3punxa div {
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-allva3punxa 1s cubic-bezier(0,0.2,0.8,1) infinite;
}.ldio-allva3punxa div:nth-child(1) {
  border-color: #e90c59;
  animation-delay: 0s;
}
.ldio-allva3punxa div:nth-child(2) {
  border-color: #46dff0;
  animation-delay: -0.5s;
}
.loadingio-spinner-ripple-b5yvo04stvj {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-allva3punxa {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-allva3punxa div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>